# Generated by Django 4.2 on 2024-03-19 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='URL-категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='URL')),
                ('article', models.IntegerField(null=True, unique=True, verbose_name='Артикль')),
                ('description', models.TextField(max_length=5000, null=True, verbose_name='Описание товара')),
                ('yarn', models.CharField(max_length=100, null=True, verbose_name='Название пряжи')),
                ('composition', models.CharField(max_length=100, null=True, verbose_name='Состав')),
                ('additional_materials', models.CharField(max_length=100, null=True, verbose_name='Доп. материалы')),
                ('color', models.CharField(max_length=60, verbose_name='Цвет')),
                ('main_photo', models.ImageField(null=True, upload_to='main_photo', verbose_name='Основное_фото')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='goods.categorygoods', verbose_name='категории')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежды',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['slug'], name='goods_goods_slug_7f4ed1_idx'),
        ),
    ]
